// SPDX-License-Identifier: MIT
// Copyright (c) 2026 ShadowSocketProxy contributors
//! Fixed-layout, versioned user/kernel device messages.

use core::{fmt, mem::size_of};

/// Current device ABI version.
pub const ABI_VERSION: u16 = 1;
/// Number of bytes in every session nonce.
pub const SESSION_NONCE_SIZE: usize = 32;
/// Default Windows device path exposed by the broker component.
pub const DEVICE_PATH: &str = r"\\.\ShadowSocketProxy";
/// Maximum request payload accepted by the device contract.
pub const MAX_PAYLOAD_SIZE: usize = 16 * 1024;
/// Maximum time the driver keeps a broker mapping exchange outstanding.
pub const MAPPING_TIMEOUT_MS: u64 = 5_000;

/// Stable status values exchanged over the device boundary.
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Status {
    /// The operation completed successfully.
    Ok = 0,
    /// The caller supplied an unsupported ABI version or structure size.
    InvalidAbi = 1,
    /// The session nonce does not match the open broker session.
    InvalidSession = 2,
    /// The request ID or generation is invalid or stale.
    InvalidIdentity = 3,
    /// The request is not valid for the current device state.
    InvalidState = 4,
    /// The requested operation is not supported by this component.
    NotSupported = 5,
    /// A required WSK or device resource is unavailable.
    ResourceUnavailable = 6,
    /// The device operation was cancelled.
    Cancelled = 7,
    /// An unspecified device failure occurred.
    InternalError = 8,
    /// The synthetic or original tuple failed exact mapping validation.
    InvalidMapping = 9,
    /// The bounded mapping wait expired without a flow.
    Timeout = 10,
}

impl Status {
    /// Converts a wire value without accepting unknown status values.
    pub const fn from_raw(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Ok),
            1 => Some(Self::InvalidAbi),
            2 => Some(Self::InvalidSession),
            3 => Some(Self::InvalidIdentity),
            4 => Some(Self::InvalidState),
            5 => Some(Self::NotSupported),
            6 => Some(Self::ResourceUnavailable),
            7 => Some(Self::Cancelled),
            8 => Some(Self::InternalError),
            9 => Some(Self::InvalidMapping),
            10 => Some(Self::Timeout),
            _ => None,
        }
    }
}

/// Device operations. Values are part of the versioned ABI.
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    /// Establishes a broker session and returns the device nonce.
    OpenSession = 1,
    /// Closes a broker session.
    CloseSession = 2,
    /// Submits a forwarding request to the device.
    SubmitRequest = 3,
    /// Retrieves a completed forwarding request.
    CompleteRequest = 4,
}

impl Opcode {
    /// Converts a wire value without accepting unknown opcodes.
    pub const fn from_raw(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::OpenSession),
            2 => Some(Self::CloseSession),
            3 => Some(Self::SubmitRequest),
            4 => Some(Self::CompleteRequest),
            _ => None,
        }
    }
}

/// Fixed-size nonce identifying one broker/device session.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct SessionNonce {
    /// Opaque nonce bytes generated by the device.
    pub bytes: [u8; SESSION_NONCE_SIZE],
}

impl SessionNonce {
    /// Creates a nonce from fixed-size bytes.
    pub const fn new(bytes: [u8; SESSION_NONCE_SIZE]) -> Self {
        Self { bytes }
    }

    /// Returns the all-zero nonce used only as an invalid sentinel.
    pub const fn zero() -> Self {
        Self {
            bytes: [0; SESSION_NONCE_SIZE],
        }
    }

    /// Rejects the invalid all-zero session identity.
    pub const fn is_zero(&self) -> bool {
        let mut index = 0;
        while index < SESSION_NONCE_SIZE {
            if self.bytes[index] != 0 {
                return false;
            }
            index += 1;
        }
        true
    }
}

impl fmt::Debug for SessionNonce {
    /// Redacts the nonce while retaining a useful type label.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_tuple("SessionNonce")
            .field(&"[redacted]")
            .finish()
    }
}

/// Monotonic broker request identity.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct RequestId(pub u64);

/// Monotonic request incarnation used to reject stale completions.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Generation(pub u64);

/// Common header present at the start of every device message.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AbiHeader {
    /// ABI version of the message.
    pub version: u16,
    /// Complete structure size in bytes.
    pub size: u16,
    /// Operation code.
    pub opcode: u32,
    /// Device status; requests use `Status::Ok`.
    pub status: u32,
    /// Session identity.
    pub session_nonce: SessionNonce,
    /// Explicitly zeroed replacement for the C ABI alignment padding.
    pub reserved: u32,
    /// Request identity.
    pub request_id: RequestId,
    /// Request incarnation.
    pub generation: Generation,
}

impl AbiHeader {
    /// Creates a request header with a validated ABI version and identity.
    pub const fn request(
        opcode: Opcode,
        nonce: SessionNonce,
        request_id: RequestId,
        generation: Generation,
        size: usize,
    ) -> Self {
        Self {
            version: ABI_VERSION,
            size: size as u16,
            opcode: opcode as u32,
            status: Status::Ok as u32,
            session_nonce: nonce,
            reserved: 0,
            request_id,
            generation,
        }
    }

    /// Creates a response header preserving the request identity.
    pub const fn response(
        opcode: Opcode,
        status: Status,
        nonce: SessionNonce,
        request_id: RequestId,
        generation: Generation,
        size: usize,
    ) -> Self {
        Self {
            version: ABI_VERSION,
            size: size as u16,
            opcode: opcode as u32,
            status: status as u32,
            session_nonce: nonce,
            reserved: 0,
            request_id,
            generation,
        }
    }

    /// Validates the version, size, opcode, and request status fields.
    pub fn validate_envelope(&self, opcode: Opcode, expected_size: usize) -> Result<(), AbiError> {
        if self.version != ABI_VERSION || self.size as usize != expected_size {
            return Err(AbiError::InvalidAbi);
        }
        if Opcode::from_raw(self.opcode) != Some(opcode) {
            return Err(AbiError::InvalidOpcode);
        }
        if self.status != Status::Ok as u32 {
            return Err(AbiError::InvalidStatus(self.status));
        }
        if self.reserved != 0 {
            return Err(AbiError::InvalidAbi);
        }
        Ok(())
    }

    /// Validates common wire fields and the expected operation and size.
    pub fn validate(
        &self,
        opcode: Opcode,
        expected_size: usize,
        expected_nonce: Option<SessionNonce>,
    ) -> Result<(), AbiError> {
        self.validate_envelope(opcode, expected_size)?;
        if self.request_id.0 == 0 || self.generation.0 == 0 {
            return Err(AbiError::InvalidIdentity);
        }
        if let Some(expected) = expected_nonce {
            if self.session_nonce != expected {
                return Err(AbiError::InvalidSession);
            }
        } else if self.session_nonce.is_zero() {
            return Err(AbiError::InvalidSession);
        }
        Ok(())
    }

    /// Validates that a response belongs to the supplied request identity.
    pub fn validate_identity(
        &self,
        request_id: RequestId,
        generation: Generation,
    ) -> Result<(), AbiError> {
        if self.request_id != request_id || self.generation != generation {
            return Err(AbiError::InvalidIdentity);
        }
        Ok(())
    }

    /// Validates a response envelope while preserving its device status.
    pub fn validate_response(
        &self,
        opcode: Opcode,
        expected_size: usize,
        expected_nonce: SessionNonce,
        request_id: RequestId,
        generation: Generation,
    ) -> Result<Status, AbiError> {
        self.validate_response_envelope(opcode, expected_size)?;
        let status = Status::from_raw(self.status).ok_or(AbiError::InvalidStatus(self.status))?;
        if self.session_nonce != expected_nonce {
            return Err(AbiError::InvalidSession);
        }
        self.validate_identity(request_id, generation)?;
        Ok(status)
    }

    /// Validates response fields that are independent of the device status.
    pub fn validate_response_envelope(
        &self,
        opcode: Opcode,
        expected_size: usize,
    ) -> Result<(), AbiError> {
        if self.version != ABI_VERSION || self.size as usize != expected_size {
            return Err(AbiError::InvalidAbi);
        }
        if Opcode::from_raw(self.opcode) != Some(opcode) {
            return Err(AbiError::InvalidOpcode);
        }
        if self.reserved != 0 {
            return Err(AbiError::InvalidAbi);
        }
        Ok(())
    }

    /// Validates a new request identity against the previous operation.
    pub fn validate_next_identity(
        &self,
        previous_request_id: RequestId,
        previous_generation: Generation,
    ) -> Result<(), AbiError> {
        if self.request_id.0 == 0
            || self.generation.0 == 0
            || self.request_id <= previous_request_id
            || self.generation <= previous_generation
        {
            return Err(AbiError::InvalidIdentity);
        }
        Ok(())
    }
}

/// Session-open request.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenSessionRequest {
    /// Common request header.
    pub header: AbiHeader,
    /// Caller nonce, allowing the broker to correlate a response.
    pub client_nonce: SessionNonce,
}

/// Session-open response.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenSessionResponse {
    /// Common response header.
    pub header: AbiHeader,
    /// Device-generated session nonce.
    pub session_nonce: SessionNonce,
}

/// Session-close request.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CloseSessionRequest {
    /// Common request header.
    pub header: AbiHeader,
}

/// Legacy bounded forwarding metadata retained for ABI compatibility.
///
/// The live WSK path uses [`MappingWaitRequest`], [`MappingRequest`], and
/// [`MappingCompletion`] and never sends payload bytes through an IOCTL.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ForwardRequest {
    /// Common request header.
    pub header: AbiHeader,
    /// IP protocol number (TCP or UDP).
    pub protocol: u8,
    /// Address family: 4 or 6.
    pub address_family: u8,
    /// Reserved for ABI alignment and future flags.
    pub reserved: u16,
    /// Source port in host byte order.
    pub source_port: u16,
    /// Destination port in host byte order.
    pub destination_port: u16,
    /// Source address in network byte order, IPv4 stored in the first four
    /// bytes.
    pub source_address: [u8; 16],
    /// Destination address in network byte order, IPv4 stored in the first
    /// four bytes.
    pub destination_address: [u8; 16],
    /// Payload bytes carried in the corresponding IOCTL buffer.
    pub payload_length: u32,
}

/// Legacy completion metadata retained for ABI compatibility.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ForwardResponse {
    /// Common response header.
    pub header: AbiHeader,
    /// Number of response bytes in the output IOCTL buffer.
    pub payload_length: u32,
    /// Reserved for ABI alignment.
    pub reserved: u32,
}

/// A fixed tuple used by the inverted-call mapping exchange.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MappingTuple {
    /// IP protocol number (TCP or UDP).
    pub protocol: u8,
    /// Address family: 4 or 6.
    pub address_family: u8,
    /// Reserved for ABI alignment and future flags.
    pub reserved: u16,
    /// Source port in host byte order.
    pub source_port: u16,
    /// Destination port in host byte order.
    pub destination_port: u16,
    /// Source address in network byte order, IPv4 stored in the first four
    /// bytes.
    pub source_address: [u8; 16],
    /// Destination address in network byte order, IPv4 stored in the first
    /// four bytes.
    pub destination_address: [u8; 16],
}

impl MappingTuple {
    /// Validates protocol, family, alignment bytes, and address width.
    pub fn validate(&self) -> Result<(), AbiError> {
        if self.reserved != 0
            || !matches!(self.protocol, 6 | 17)
            || !matches!(self.address_family, 4 | 6)
        {
            return Err(AbiError::InvalidMapping);
        }
        if self.address_family == 4
            && (self.source_address[4..].iter().any(|byte| *byte != 0)
                || self.destination_address[4..].iter().any(|byte| *byte != 0))
        {
            return Err(AbiError::InvalidMapping);
        }
        Ok(())
    }

    /// Validates a broker-supplied original tuple for outbound use.
    pub fn validate_original(&self) -> Result<(), AbiError> {
        self.validate()?;
        if self.source_port == 0
            || self.destination_port == 0
            || self.destination_address.iter().all(|byte| *byte == 0)
        {
            return Err(AbiError::InvalidMapping);
        }
        Ok(())
    }
}

/// Input posted by the broker before the driver has a flow to report.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MappingWaitRequest {
    /// Common request header.
    pub header: AbiHeader,
}

impl MappingWaitRequest {
    /// Validates a broker's pending inverted-call request.
    pub fn validate(&self, nonce: SessionNonce) -> Result<(), AbiError> {
        self.header
            .validate(Opcode::SubmitRequest, size_of::<Self>(), Some(nonce))
    }
}

/// Mapping request completed by the driver when a new flow arrives.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MappingRequest {
    /// Common response header carrying the flow identity.
    pub header: AbiHeader,
    /// Synthetic tuple observed by the WSK listener.
    pub synthetic: MappingTuple,
}

impl MappingRequest {
    /// Validates a mapping request emitted by the driver.
    pub fn validate(&self, nonce: SessionNonce) -> Result<(), AbiError> {
        self.header
            .validate(Opcode::SubmitRequest, size_of::<Self>(), Some(nonce))?;
        self.synthetic.validate()
    }
}

/// Broker completion containing the original tuple for one flow.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MappingCompletion {
    /// Common completion header preserving the flow identity.
    pub header: AbiHeader,
    /// Echo of the synthetic tuple that was requested.
    pub synthetic: MappingTuple,
    /// Original tuple returned by the authenticated broker.
    pub original: MappingTuple,
}

impl MappingCompletion {
    /// Validates identity, exact synthetic-tuple correlation, and the
    /// broker-supplied original destination.
    pub fn validate(
        &self,
        nonce: SessionNonce,
        request_id: RequestId,
        generation: Generation,
        expected_synthetic: MappingTuple,
    ) -> Result<(), AbiError> {
        self.header
            .validate(Opcode::CompleteRequest, size_of::<Self>(), Some(nonce))?;
        self.header.validate_identity(request_id, generation)?;
        self.synthetic.validate()?;
        self.original.validate_original()?;
        if self.synthetic != expected_synthetic
            || self.original.protocol != expected_synthetic.protocol
            || self.original.address_family != expected_synthetic.address_family
        {
            return Err(AbiError::InvalidMapping);
        }
        Ok(())
    }
}

impl ForwardRequest {
    /// Validates forwarding metadata and its fixed payload bound.
    pub fn validate(&self, nonce: SessionNonce) -> Result<(), AbiError> {
        self.header
            .validate(Opcode::SubmitRequest, size_of::<Self>(), Some(nonce))?;
        if self.reserved != 0
            || !matches!(self.protocol, 6 | 17)
            || !matches!(self.address_family, 4 | 6)
            || self.payload_length as usize > MAX_PAYLOAD_SIZE
        {
            return Err(AbiError::InvalidMapping);
        }
        if self.address_family == 4
            && (self.source_address[4..].iter().any(|byte| *byte != 0)
                || self.destination_address[4..].iter().any(|byte| *byte != 0))
        {
            return Err(AbiError::InvalidMapping);
        }
        Ok(())
    }
}

impl ForwardResponse {
    /// Validates completion metadata and its fixed payload bound.
    pub fn validate(
        &self,
        nonce: SessionNonce,
        request_id: RequestId,
        generation: Generation,
    ) -> Result<(), AbiError> {
        self.header
            .validate(Opcode::CompleteRequest, size_of::<Self>(), Some(nonce))?;
        self.header.validate_identity(request_id, generation)?;
        if self.reserved != 0 || self.payload_length as usize > MAX_PAYLOAD_SIZE {
            return Err(AbiError::InvalidMapping);
        }
        Ok(())
    }
}

/// Stable IOCTL code values used by the broker.
pub mod ioctl {
    /// Windows `FILE_DEVICE_NETWORK`.
    pub const FILE_DEVICE_NETWORK: u32 = 0x12;
    /// Buffered IOCTL method.
    const METHOD_BUFFERED: u32 = 0;
    /// Require a handle opened for both device read and write access.
    const FILE_READ_DATA: u32 = 0x0001;
    /// Require write access in every broker IOCTL.
    const FILE_WRITE_DATA: u32 = 0x0002;
    /// Access bits encoded into every broker IOCTL.
    const FILE_READ_WRITE_ACCESS: u32 = FILE_READ_DATA | FILE_WRITE_DATA;

    /// Builds one stable Windows control code.
    const fn ctl_code(function: u32) -> u32 {
        (FILE_DEVICE_NETWORK << 16)
            | (FILE_READ_WRITE_ACCESS << 14)
            | (function << 2)
            | METHOD_BUFFERED
    }

    /// Opens a versioned broker/device session.
    pub const OPEN_SESSION: u32 = ctl_code(0x800);
    /// Closes a versioned broker/device session.
    pub const CLOSE_SESSION: u32 = ctl_code(0x801);
    /// Posts one inverted-call mapping wait.
    pub const SUBMIT_REQUEST: u32 = ctl_code(0x802);
    /// Completes one inverted-call mapping request.
    pub const COMPLETE_REQUEST: u32 = ctl_code(0x803);
}

/// ABI validation failures.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AbiError {
    /// Version or fixed structure size mismatch.
    InvalidAbi,
    /// Unknown or unexpected operation.
    InvalidOpcode,
    /// Unknown or non-success status.
    InvalidStatus(u32),
    /// Zero request ID or generation.
    InvalidIdentity,
    /// Missing or mismatched nonce.
    InvalidSession,
    /// Forwarding metadata is not valid for the fixed mapping ABI.
    InvalidMapping,
}

impl AbiError {
    /// Maps a validation failure to the stable wire status.
    pub const fn status(self) -> Status {
        match self {
            Self::InvalidAbi => Status::InvalidAbi,
            Self::InvalidOpcode => Status::InvalidAbi,
            Self::InvalidStatus(_) => Status::InvalidAbi,
            Self::InvalidIdentity => Status::InvalidIdentity,
            Self::InvalidSession => Status::InvalidSession,
            Self::InvalidMapping => Status::InvalidMapping,
        }
    }
}

impl fmt::Display for AbiError {
    /// Formats an ABI validation failure without exposing session data.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidAbi => write!(formatter, "invalid ABI version or structure size"),
            Self::InvalidOpcode => write!(formatter, "unexpected device opcode"),
            Self::InvalidStatus(status) => write!(formatter, "device returned status {status}"),
            Self::InvalidIdentity => write!(formatter, "request ID and generation must be nonzero"),
            Self::InvalidSession => write!(formatter, "invalid device session nonce"),
            Self::InvalidMapping => write!(formatter, "invalid forwarding mapping metadata"),
        }
    }
}

impl core::error::Error for AbiError {}

/// Compile-time assertion for the common header layout.
const _: () = assert!(size_of::<AbiHeader>() == 64);
/// Compile-time assertion for the nonce layout.
const _: () = assert!(size_of::<SessionNonce>() == SESSION_NONCE_SIZE);
/// Compile-time assertion for the open request layout.
const _: () = assert!(size_of::<OpenSessionRequest>() == 96);
/// Compile-time assertion for the open response layout.
const _: () = assert!(size_of::<OpenSessionResponse>() == 96);
/// Compile-time assertion for the close request layout.
const _: () = assert!(size_of::<CloseSessionRequest>() == 64);
/// Compile-time assertion for the forwarding request layout.
const _: () = assert!(size_of::<ForwardRequest>() == 112);
/// Compile-time assertion for the forwarding response layout.
const _: () = assert!(size_of::<ForwardResponse>() == 72);
/// Compile-time assertion for the mapping tuple layout.
const _: () = assert!(size_of::<MappingTuple>() == 40);
/// Compile-time assertion for the pending mapping request layout.
const _: () = assert!(size_of::<MappingWaitRequest>() == 64);
/// Compile-time assertion for the emitted mapping request layout.
const _: () = assert!(size_of::<MappingRequest>() == 104);
/// Compile-time assertion for the mapping completion layout.
const _: () = assert!(size_of::<MappingCompletion>() == 144);

#[cfg(test)]
mod tests {
    use super::*;
    use std::format;

    fn nonce(value: u8) -> SessionNonce {
        SessionNonce::new([value; SESSION_NONCE_SIZE])
    }

    #[test]
    fn validates_fixed_header_and_identity() {
        let header = AbiHeader::request(
            Opcode::SubmitRequest,
            nonce(7),
            RequestId(1),
            Generation(2),
            size_of::<ForwardRequest>(),
        );
        assert!(header
            .validate(
                Opcode::SubmitRequest,
                size_of::<ForwardRequest>(),
                Some(nonce(7))
            )
            .is_ok());
        assert_eq!(
            header.validate(
                Opcode::CloseSession,
                size_of::<ForwardRequest>(),
                Some(nonce(7))
            ),
            Err(AbiError::InvalidOpcode)
        );
    }

    #[test]
    fn rejects_zero_nonce_and_stale_identity() {
        let header = AbiHeader::request(
            Opcode::OpenSession,
            SessionNonce::zero(),
            RequestId(0),
            Generation(0),
            size_of::<OpenSessionRequest>(),
        );
        assert_eq!(
            header.validate(Opcode::OpenSession, size_of::<OpenSessionRequest>(), None),
            Err(AbiError::InvalidIdentity)
        );
    }

    #[test]
    fn nonce_debug_does_not_disclose_bytes() {
        assert_eq!(format!("{:?}", nonce(0xab)), "SessionNonce(\"[redacted]\")");
    }

    #[test]
    fn validates_mapping_metadata_and_completion_identity() {
        let session = nonce(7);
        let request = ForwardRequest {
            header: AbiHeader::request(
                Opcode::SubmitRequest,
                session,
                RequestId(4),
                Generation(5),
                size_of::<ForwardRequest>(),
            ),
            protocol: 6,
            address_family: 4,
            reserved: 0,
            source_port: 1000,
            destination_port: 2000,
            source_address: [1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            destination_address: [5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            payload_length: 12,
        };
        assert!(request.validate(session).is_ok());

        let response = ForwardResponse {
            header: AbiHeader::response(
                Opcode::CompleteRequest,
                Status::Ok,
                session,
                RequestId(4),
                Generation(5),
                size_of::<ForwardResponse>(),
            ),
            payload_length: 12,
            reserved: 0,
        };
        assert!(response
            .validate(session, RequestId(4), Generation(5))
            .is_ok());
    }

    #[test]
    fn rejects_mapping_reserved_bytes_and_stale_completion() {
        let session = nonce(7);
        let request = ForwardRequest {
            header: AbiHeader::request(
                Opcode::SubmitRequest,
                session,
                RequestId(4),
                Generation(5),
                size_of::<ForwardRequest>(),
            ),
            protocol: 6,
            address_family: 4,
            reserved: 1,
            source_port: 0,
            destination_port: 0,
            source_address: [0; 16],
            destination_address: [0; 16],
            payload_length: 0,
        };
        assert_eq!(request.validate(session), Err(AbiError::InvalidMapping));
        let response = ForwardResponse {
            header: AbiHeader::response(
                Opcode::CompleteRequest,
                Status::Ok,
                session,
                RequestId(4),
                Generation(5),
                size_of::<ForwardResponse>(),
            ),
            payload_length: 0,
            reserved: 0,
        };
        assert_eq!(
            response.validate(session, RequestId(9), Generation(5)),
            Err(AbiError::InvalidIdentity)
        );
    }

    #[test]
    fn validates_inverted_mapping_correlation_and_original_tuple() {
        let session = nonce(8);
        let synthetic = MappingTuple {
            protocol: 6,
            address_family: 4,
            reserved: 0,
            source_port: 40000,
            destination_port: 15000,
            source_address: [10, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            destination_address: [10, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        };
        let completion = MappingCompletion {
            header: AbiHeader::request(
                Opcode::CompleteRequest,
                session,
                RequestId(11),
                Generation(12),
                size_of::<MappingCompletion>(),
            ),
            synthetic,
            original: MappingTuple {
                destination_address: [192, 0, 2, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                destination_port: 443,
                source_address: synthetic.source_address,
                source_port: synthetic.source_port,
                protocol: synthetic.protocol,
                address_family: synthetic.address_family,
                reserved: 0,
            },
        };
        assert!(completion
            .validate(session, RequestId(11), Generation(12), synthetic)
            .is_ok());

        let mut mismatch = completion;
        mismatch.synthetic.destination_port += 1;
        assert_eq!(
            mismatch.validate(session, RequestId(11), Generation(12), synthetic),
            Err(AbiError::InvalidMapping)
        );
    }

    #[test]
    fn ioctl_codes_require_read_and_write_access() {
        for code in [
            ioctl::OPEN_SESSION,
            ioctl::CLOSE_SESSION,
            ioctl::SUBMIT_REQUEST,
            ioctl::COMPLETE_REQUEST,
        ] {
            assert_eq!((code >> 14) & 0x3, 0x3);
        }
    }
}
