# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ShadowSocketProxy contributors

[workspace]
members = [
    "crates/bpf/fixture-runner",
    "crates/control-service",
    "crates/e2e-runner",
    "crates/host-proxy",
    "crates/tls-rustls",
    "crates/wsk-driver",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
